=== github188/cap-other/cap-document/build/resources/main/DocConfig.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="WtDocConfig" type="DocConfigType"/>

  <xs:complexType name="DocConfigType">
    <xs:sequence>
      <xs:element name="MarkText" type="xs:string" minOccurs="0"/>
      <xs:element name="NullValueText" type="xs:string" minOccurs="0"/>
      <xs:element name="DirText" type="xs:string" minOccurs="0"/>
      <xs:element name="WtSection" type="SectionElementType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="version" type="xs:string"/>
    <xs:attribute name="docNamePattern" type="xs:string"/>
    <xs:attribute name="bizDomainPattern" type="xs:string"/>
    <xs:attribute name="diffKey" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="SectionElementType">
    <xs:complexContent>
      <xs:extension base="ContainerElementType">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="WtChapter" type="ChapterElementType" nillable="true"/>
            <xs:element name="span" type="ContentSegElementType" nillable="true"/>
            <xs:element name="table" type="TableElementType" nillable="true"/>
            <xs:element name="WtEmbed" type="EmbedObjectElementType" nillable="true"/>
            <xs:element name="WtGraphic" type="GraphicElementType" nillable="true"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ContainerElementType">
    <xs:complexContent>
      <xs:extension base="ConfigElementType">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ConfigElementType" abstract="true">
    <xs:sequence/>
    <xs:attribute name="mappingTo" type="xs:string"/>
    <xs:attribute name="optional" type="xs:boolean"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="maxOccurs" type="xs:int"/>
  </xs:complexType>

  <xs:complexType name="ChapterElementType">
    <xs:complexContent>
      <xs:extension base="ContainerElementType">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="WtChapter" type="ChapterElementType"/>
            <xs:element name="span" type="ContentSegElementType"/>
            <xs:element name="table" type="TableElementType"/>
            <xs:element name="WtEmbed" type="EmbedObjectElementType"/>
            <xs:element name="WtGraphic" type="GraphicElementType"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="type" type="chapterType" use="required"/>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="fillDescription" type="xs:string"/>
        <xs:attribute name="titleAsSelector" type="xs:boolean"/>
        <xs:attribute name="enable" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ContentSegElementType">
    <xs:complexContent>
      <xs:extension base="ConfigElementType">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TableElementType">
    <xs:complexContent>
      <xs:extension base="ContentSegElementType">
        <xs:sequence>
          <xs:element name="tr" type="TableRowElementType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="type" type="tableType" use="required"/>
        <xs:attribute name="fillDescription" type="xs:string"/>
        <xs:attribute name="descriptionBefore" type="xs:string"/>
        <xs:attribute name="needStore" type="xs:boolean"/>
        <xs:attribute name="selector" type="xs:string"/>
        <xs:attribute name="width" type="xs:float"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TableRowElementType">
    <xs:complexContent>
      <xs:extension base="ConfigElementType">
        <xs:sequence>
          <xs:element name="td" type="TableCellElementType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="extRow" type="xs:boolean"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TableCellElementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="mappingTo" type="xs:string"/>
        <xs:attribute name="optional" type="xs:boolean"/>
        <xs:attribute name="nullAble" type="xs:boolean"/>
        <xs:attribute name="mergeCellType" type="mergeCellType"/>
        <xs:attribute name="colspan" type="xs:int"/>
        <xs:attribute name="rowspan" type="xs:int"/>
        <xs:attribute name="extCell" type="xs:boolean"/>
        <xs:attribute name="extData" type="xs:string"/>
        <xs:attribute name="headerLabel" type="xs:string"/>
        <xs:attribute name="valueKey" type="xs:string"/>
        <xs:attribute name="storeStrategy" type="dataStoreStrategy"/>
        <xs:attribute name="width" type="xs:float"/>
        <xs:attribute name="contentType" type="cellContentType"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="EmbedObjectElementType">
    <xs:complexContent>
      <xs:extension base="ContentSegElementType">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="GraphicElementType">
    <xs:complexContent>
      <xs:extension base="ContentSegElementType">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="chapterType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FIXED"/>
      <xs:enumeration value="DYNAMIC"/>
      <xs:enumeration value="MANUAL"/>
      <xs:enumeration value="UNDEFINED"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="mergeCellType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE"/>
      <xs:enumeration value="HORIZONTAL"/>
      <xs:enumeration value="VERTICAL"/>
      <xs:enumeration value="BOTH"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dataStoreStrategy">
    <xs:restriction base="xs:string">
      <xs:enumeration value="STORE"/>
      <xs:enumeration value="NO_STORE"/>
      <xs:enumeration value="NULL_VALUE_NO_STORE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="cellContentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SIMPLEX"/>
      <xs:enumeration value="COMPLEX"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tableType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EXT_ROWS"/>
      <xs:enumeration value="EXT_COLS"/>
      <xs:enumeration value="FIXED"/>
      <xs:enumeration value="UNKNOWN"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== github188/cap-other/cap-webapp/src/main/webapp/WEB-INF/docconfig/docconfig-dbd.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<WtDocConfig diffKey="数据库设计" version="1.0" name="数据库设计说明文档V1.1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../classes/DocConfig.xsd"
>
	<WtSection name="正文">
		
		<WtChapter title="数据库E-R关系图" type="FIXED" >
			 <WtGraphic mappingTo="$CAPDocDBHelper_getDataBaseErGraphHtml($packageId,$cookiesJsonStr,$httpUrl)"/> <!---->
		</WtChapter>
		
		<WtChapter title="数据库对象清单" type="FIXED">
			<WtChapter title="数据表对象清单" type="FIXED">
				<table type="EXT_ROWS" name="数据表列表" mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=1)">
					<tr>
						<td mappingTo="objectItem.name" nullAble="true">Name</td>
						<td mappingTo="objectItem.code" nullAble="true">Code</td>
						<td mappingTo="objectItem.comment" nullAble="true">Comment</td>
					</tr>
				</table>
			</WtChapter>
			
			<WtChapter title="视图对象清单" type="FIXED">
				<table type="EXT_ROWS" name="数据表列表" mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=2)">
					<tr>
						<td mappingTo="objectItem.name" nullAble="true">Name</td>
						<td mappingTo="objectItem.code" nullAble="true">Code</td>
						<td mappingTo="objectItem.comment" nullAble="true">Comment</td>
					</tr>
				</table>
			</WtChapter>
			
			<WtChapter title="存储过程清单" type="FIXED">
				<table type="EXT_ROWS" name="存储过程列表" mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=3)">
					<tr>
						<td mappingTo="objectItem.name" nullAble="true">Name</td>
						<td mappingTo="objectItem.code" nullAble="true">Code</td>
						<td mappingTo="objectItem.comment" nullAble="true">Comment</td>
					</tr>
				</table>
			</WtChapter>
			
			<WtChapter title="函数清单" type="FIXED">
				<table type="EXT_ROWS" name="函数列表" mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=4)">
					<tr>
						<td mappingTo="objectItem.name" nullAble="true">Name</td>
						<td mappingTo="objectItem.code" nullAble="true">Code</td>
						<td mappingTo="objectItem.comment" nullAble="true">Comment</td>
					</tr>
				</table>
			</WtChapter>
			
		</WtChapter>
		
		<WtChapter title="数据库对象结构" type="FIXED">
		
			<WtChapter title="数据表结构" type="FIXED">			
				<WtChapter title="$StringUtils_getDBObjectTitle(objectItem.name,objectItem.code)" type="DYNAMIC"
					mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=1)">
					<table type="EXT_ROWS" name="数据表结构"  mappingTo="columnItem[]=objectItem.columnList">
						<tr>
							<td mappingTo="columnItem.name" nullAble="true" width="2.5">Name</td>
							<td mappingTo="columnItem.code" nullAble="true"  width="3">Code</td>
							<td mappingTo="columnItem.dataType" nullAble="true"  width="2.5">Data Type</td>
							<td mappingTo="columnItem.length" nullAble="true"  width="2">length</td>
							<td mappingTo="columnItem.precision" nullAble="true" width="1">precision</td>
							<td mappingTo="columnItem.enableNull" nullAble="true" width="1">null?</td>						
							<td mappingTo="columnItem.comment" nullAble="true" width="3">Comment</td>
						</tr>
					</table>
				</WtChapter>
			</WtChapter>
			
			<WtChapter title="视图结构" type="FIXED">			
				<WtChapter title="$StringUtils_getDBObjectTitle(objectItem.name,objectItem.code)" type="DYNAMIC"
					mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=2)">
					<table type="EXT_ROWS" name="视图结构"  mappingTo="columnItem[]=objectItem.columnList">
						<tr>
							<td mappingTo="columnItem.name" nullAble="true" width="3">Name</td>
							<td mappingTo="columnItem.code" nullAble="true" width="3">Code</td>
							<td mappingTo="columnItem.dataType" nullAble="true" width="3">Data Type</td>	
							<td mappingTo="columnItem.length" nullAble="true" width="2">length</td>
							<td mappingTo="columnItem.precision" nullAble="true" width="1">precision</td>					
							<td mappingTo="columnItem.comment" nullAble="true" width="3">Comment</td>
						</tr>
					</table>
				</WtChapter>
			</WtChapter>
			
			<WtChapter title="存储过程结构" type="FIXED">			
				<WtChapter title="$StringUtils_getDBObjectTitle(objectItem.name,objectItem.code)" type="DYNAMIC"
					mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=3)">
					<table type="EXT_ROWS" name="存储过程结构"  mappingTo="columnItem[]=objectItem.columnList">
						<tr>
							<td mappingTo="columnItem.code" nullAble="true" width="3.5">Code</td>
							<td mappingTo="columnItem.columnType" nullAble="true" width="3.5">Param Type</td>
							<td mappingTo="columnItem.dataType" nullAble="true" width="3.5">Data Type</td>	
							<td mappingTo="columnItem.length" nullAble="true" width="2">length</td>				
							<td mappingTo="columnItem.comment" nullAble="true" width="3.5">Comment</td>
						</tr>
					</table>
				</WtChapter>
			</WtChapter>
			
			<WtChapter title="函数结构" type="FIXED">			
				<WtChapter title="$StringUtils_getDBObjectTitle(objectItem.name,objectItem.code)" type="DYNAMIC"
					mappingTo="objectItem[]=#DBObject(packageId=$packageId,type=4)">
					<table type="EXT_ROWS" name="函数结构"  mappingTo="columnItem[]=objectItem.columnList">
						<tr>
							<td mappingTo="columnItem.code" nullAble="true" width="3.5">Code</td>
							<td mappingTo="columnItem.columnType" nullAble="true" width="3.5">Param Type</td>
							<td mappingTo="columnItem.dataType" nullAble="true" width="3.5">Data Type</td>	
							<td mappingTo="columnItem.length" nullAble="true" width="2">length</td>				
							<td mappingTo="columnItem.comment" nullAble="true" width="3.5">Comment</td>
						</tr>
					</table>
				</WtChapter>
			</WtChapter>
			
		</WtChapter>
	</WtSection>
</WtDocConfig>
